version: "3.9"
services:
  web_api:
    image: web_api_smart_locker
    container_name: web_api_smart_locker_app
    ports:
      - "5000:5000"
  sql-server:
    # image: mcr.microsoft.com/mssql/server:2019-GA-ubuntu-16.04
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sql_server
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
      - MSSQL_SA_PASSWORD=ab8mbu3t053tEn8
      - MSSQL_COLLATION=Thai_CI_AS